fix(kaktoos-assimilator): move file open into try
minecrafthome/minecrafthome pull request #60
Opened 2020-11-11 11:51 UTC by BoySanic

Moved file open function call into the try/catch block below it for fault tolerance in the case that the assimilator is unable to open the file.

2020-11-11 12:26 UTC, hube12 requested changes
#28

2020-11-11 12:26 UTC, hube12 commented on images/makeproject/project/bin/kaktoos_assimilator.py
>                  with open(os.path.join(path, filename), "a") as f:
Also guard this but instead if fail report the error in logs_error

2020-11-12 21:11 UTC, hube12 approved these changes

2020-11-12 21:44 UTC, hube12 commented on images/makeproject/project/bin/kaktoos_assimilator.py
>                  except OSError:
except OSError as e:
   print(e.filename)

2020-11-13 00:15 UTC, BoySanic commented
I made the changes we originally discussed, with splitting the try/except block into 3 separate blocks for each error point we could hit

2020-11-13 08:43 UTC, hube12 approved these changes

2020-11-14 13:20 UTC, ChipWolf approved these changes

2020-11-14 15:01 UTC, vcokltfre approved these changes

2020-11-14 21:57 UTC, merged