fix(boinc): fix kaktwoos validator regex and 20% perf increase
minecrafthome/minecrafthome pull request #68
Opened 2021-02-01 02:06 UTC by Hyenadae

With @BalintCsala and his changes, we get roughly 15-20% more performance in our OpenCL kernel for just about no tradeoffs

Vega 56 went from 42 -> 51m/s (million seeds a second)
GTX 2060 Super went from 52 -> 60m/s 

Please verify seeds and outputs further

2021-02-01 02:08 UTC, BoySanic commented
Do we want a version number increment or is it not necessary?

2021-02-01 02:08 UTC, Hyenadae commented
It's kinda necessary as it helps BOINC push stuff through in an obvious way

2021-02-01 02:18 UTC, BoySanic commented
Nevermind I misunderstood what I was reading. 

I'm just gonna run our baseline WU to make sure I get the same result and then otherwise it looks good to me

2021-02-02 21:30 UTC, hube12 requested changes

2021-02-03 15:05 UTC, Hyenadae commented
Alright, so we're making progress towards testing enough GPUs to confirm that the 'AMD' and 'Nvidia' kernels are basically what they should be (better on one vendor's GPUs than another's). Still need to test an RX 5700/XT for AMD, and a GTX 980 for Nvidia before we can do a push.

2021-02-03 15:20 UTC, hube12 commented on images/makeproject/project/bin/kaktwoos_validator_compare.py
> +seeds_1 = re.findall("Found seed: ([\s\S](:?\n|\r\n))\n", file_1.stderr_out)
oopsi it's (?: not (:?

2021-02-08 20:54 UTC, closed without merging